apiVersion: v1
kind: Secret
metadata:
  name: cephfs-storageclass-secret
  namespace: cephfs
data:
  key: QVFBNGp6MWlLK1RnSGhBQVlnQlNFRjI5VU1WOEZidndydWxVNlE9PQ==
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs-disk
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ceph.com/cephfs
parameters:
  monitors: 11.18.1.103:6789,11.18.1.104:6789,11.18.1.101:6789
  # 不能使用主机名方式，因为前面安装的 cephfs-provisioner 的 pod 是无法访问的
  #monitors: ceph01:6789,ceph02:6789,ceph03:6789
  adminId: admin
  adminSecretName: cephfs-storageclass-secret
  adminSecretNamespace: cephfs
  claimRoot: /k8s-volumes
reclaimPolicy: Retain